config/routes.rb
# Les routes qui redirigent vers les pages statiques
Rails.application.routes.draw do
  get '/', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/about/toi', to: 'static_pages#toi', as: "moi"
  get '/about/ton_groupe', to: 'static_pages#ton_groupe', as: "la_pleiade"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
# On definit les methodes qu'on utilise lors de la redirection des pages statiques

class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
  
  def toi
  end
  
  def ton_groupe
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Menu</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
            <a class="nav-link" href="<%= moi_path %>">Moi</a>
          </li>
            <a class="nav-link" href="<%= la_pleiade_path %>">Mon Groupe</a>
          </li>


        </ul>
      </div>
    </nav>
    </header>
    <div>
      <center>
      <%= yield %>
      <center>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<!-- La page about -->
<h1>About me</h1>
<p>Ore wa Francois D. Kaizoku oni naru otoko da ! </p>
<p>Pour des infos sur moi clique <a href= "<%= moi_path %>" >la</a>
<p>Pour des infos sur mon groupe clique <a href= "<%= la_pleiade_path %>" >la</a>

app/views/static_pages/contact.html.erb
<!-- La page Contact -->
<h1>Contact</h1>
<p>Got any questions or wanna make a donation ? hit me on slack : @Francois D.</p>

app/views/static_pages/home.html.erb
<!-- La page d'acceuil -->
<h1>What's up Dawg !</h1>
<p>Have a seat and order a drink !</p>
<p>We're in this shit for a couple of hours.</p>

app/views/static_pages/toi.html.erb
<!-- La page about/toi -->
<h1>Tallac</h1>

<br><p>Le grand manitou a créé les animaux du mont de Tallac en leur donnant des formes différentes, et si on prend les ours par exemple, certains sont énormes mais se régalent en mangeant des fruits et du miel, alors que d'autres sont des bêtes féroces qui déciment les troupeaux...</p>
<p>Si François appartient au deuxième groupe, celui des bêtes féroces, il continuera à attaquer les troupeaux jusqu'à la fin de ses jours c'est certain, alors la seule chance pour lui de rester en vie c'est de s'exiler dans un endroit où les Hommes ne vont jamais et où il ne risquera pas d'être abattu comme une bête malfaisante</p>

app/views/static_pages/ton_groupe.html.erb
<!-- La page about/ton_groupe -->
<h1>La Pléïade</h1>
<br><p>La Pléiade est un groupe de sept poètes français du XVIe siècle, dont Pierre de Ronsard et Joachim Du Bellay ont fait partie.<br>À travers leurs œuvres littéraires et leurs textes théoriques, leur ambition était de renouveler la langue française, afin de la rendre indépendante d'autres idiomes alors plus « nobles » comme le latin.<br>Le but politique était de participer à l'unification de la France à travers la langue française.</p>

<p>François D. est le créateur de ce groupe, le huitième et premier membre, l'Immortel, l'Alchimiste.</p>